// "What it's for" text for each drug group in parser.js (DRUG_CLASSES).
// Each entry is [group name, one-sentence explanation]. Fixed text, so nothing
// is generated on the fly. Have a native speaker review before real use.

const DRUG_INFO = {
  en: {
    label: "What it's for",
    note: "Your doctor may have prescribed it for a different reason. Ask if you are not sure.",
    classes: {
      antibiotic: ["Antibiotic", "Kills bacteria to treat infections. It does not work on colds or flu."],
      antiviral: ["Antiviral", "Fights viruses, such as those that cause cold sores, shingles, or flu."],
      antifungal: ["Antifungal", "Treats fungal infections, such as yeast infections."],
      blood_pressure: ["Blood pressure medicine", "Lowers blood pressure to protect your heart, brain, and kidneys."],
      heart_rate: ["Beta blocker", "Slows the heartbeat and lowers blood pressure. Used for high blood pressure and heart conditions."],
      water_pill: ["Water pill (diuretic)", "Helps your body get rid of extra water and salt, which reduces swelling and blood pressure."],
      cholesterol: ["Cholesterol medicine", "Lowers cholesterol to reduce the risk of heart attack and stroke."],
      diabetes: ["Diabetes medicine", "Lowers blood sugar in people with diabetes."],
      thyroid: ["Thyroid hormone", "Replaces thyroid hormone when your thyroid is underactive."],
      stomach_acid: ["Stomach acid reducer", "Reduces stomach acid to treat heartburn, acid reflux, and ulcers."],
      nausea: ["Anti-nausea medicine", "Prevents or relieves nausea, vomiting, or motion sickness."],
      antidepressant: ["Antidepressant", "Treats depression and anxiety by balancing chemicals in the brain."],
      anxiety: ["Anti-anxiety medicine", "Reduces anxiety."],
      sedative: ["Sedative", "Calms anxiety, panic, or muscle spasms. Can be habit-forming."],
      sleep: ["Sleep medicine", "Helps you fall asleep and stay asleep."],
      nerve: ["Seizure and nerve pain medicine", "Calms overactive nerves. Used for seizures and nerve pain."],
      muscle: ["Muscle relaxant", "Relaxes tight or cramping muscles."],
      pain_inflammation: ["Pain and swelling reliever (NSAID)", "Reduces pain, swelling, and fever."],
      pain_fever: ["Pain and fever reliever", "Relieves pain and lowers fever."],
      opioid: ["Strong pain medicine (opioid)", "Relieves moderate to severe pain. Can be habit-forming."],
      steroid: ["Steroid", "Reduces swelling and calms the immune system. Used for allergies, asthma, arthritis, and skin problems."],
      breathing: ["Breathing medicine", "Opens the airways or reduces swelling in them. Used for asthma, COPD, or allergies."],
      allergy: ["Antihistamine", "Relieves allergy symptoms such as sneezing, runny nose, itching, and hives."],
      blood_thinner: ["Blood thinner", "Prevents dangerous blood clots that can cause a stroke or block blood vessels."],
      antiplatelet: ["Anti-clotting medicine", "Keeps blood cells from clumping together, to help prevent heart attack and stroke."],
      gout: ["Gout medicine", "Prevents or treats gout, a painful joint swelling caused by uric acid."],
      prostate: ["Prostate medicine", "Eases urination problems caused by an enlarged prostate."],
      blood_flow: ["Blood flow medicine", "Improves blood flow. Used for erectile dysfunction or high blood pressure in the lungs."],
      hormone: ["Hormone medicine", "Used for birth control, menopause symptoms, or menstrual problems."],
      mood: ["Mood stabilizer / antipsychotic", "Helps steady mood and thinking. Used for bipolar disorder, schizophrenia, and sometimes depression."],
      adhd: ["ADHD medicine (stimulant)", "Improves focus and attention. Can be habit-forming."],
      memory: ["Memory medicine", "Helps memory and thinking in Alzheimer's disease."],
      parkinson: ["Parkinson's medicine", "Treats Parkinson's disease and restless legs syndrome."],
      migraine: ["Migraine medicine", "Stops a migraine headache after it starts."],
      supplement: ["Vitamin or mineral", "Replaces a vitamin or mineral your body is low on."],
      cough: ["Cough medicine", "Calms a cough."],
      gut_cramps: ["Stomach cramp medicine", "Relieves stomach and bowel cramps, such as from irritable bowel syndrome."],
      glaucoma: ["Eye pressure medicine", "Lowers pressure inside the eye to treat glaucoma."],
      immune: ["Immune system medicine", "Calms an overactive immune system. Used for rheumatoid arthritis, psoriasis, and some cancers."],
    },
  },

  es: {
    label: "Para qué sirve",
    note: "Su médico puede habérselo recetado por otra razón. Pregunte si tiene dudas.",
    classes: {
      antibiotic: ["Antibiótico", "Mata las bacterias para tratar infecciones. No sirve para resfriados ni gripe."],
      antiviral: ["Antiviral", "Combate virus, como los que causan herpes labial, culebrilla o gripe."],
      antifungal: ["Antimicótico", "Trata infecciones por hongos, como las infecciones por levaduras."],
      blood_pressure: ["Medicamento para la presión arterial", "Baja la presión arterial para proteger el corazón, el cerebro y los riñones."],
      heart_rate: ["Betabloqueador", "Hace más lento el ritmo del corazón y baja la presión arterial. Se usa para la presión alta y problemas del corazón."],
      water_pill: ["Diurético", "Ayuda al cuerpo a eliminar el exceso de agua y sal, lo que reduce la hinchazón y la presión arterial."],
      cholesterol: ["Medicamento para el colesterol", "Baja el colesterol para reducir el riesgo de ataque al corazón y derrame cerebral."],
      diabetes: ["Medicamento para la diabetes", "Baja el azúcar en la sangre en personas con diabetes."],
      thyroid: ["Hormona tiroidea", "Reemplaza la hormona tiroidea cuando la tiroides funciona poco."],
      stomach_acid: ["Reductor del ácido estomacal", "Reduce el ácido del estómago para tratar la acidez, el reflujo y las úlceras."],
      nausea: ["Medicamento contra las náuseas", "Previene o alivia las náuseas, los vómitos o el mareo por movimiento."],
      antidepressant: ["Antidepresivo", "Trata la depresión y la ansiedad equilibrando sustancias químicas del cerebro."],
      anxiety: ["Medicamento para la ansiedad", "Reduce la ansiedad."],
      sedative: ["Sedante", "Calma la ansiedad, el pánico o los espasmos musculares. Puede crear dependencia."],
      sleep: ["Medicamento para dormir", "Le ayuda a dormirse y a seguir dormido."],
      nerve: ["Medicamento para convulsiones y dolor de nervios", "Calma los nervios hiperactivos. Se usa para convulsiones y dolor de nervios."],
      muscle: ["Relajante muscular", "Relaja los músculos tensos o con calambres."],
      pain_inflammation: ["Antiinflamatorio (AINE)", "Reduce el dolor, la hinchazón y la fiebre."],
      pain_fever: ["Analgésico y antipirético", "Alivia el dolor y baja la fiebre."],
      opioid: ["Analgésico fuerte (opioide)", "Alivia el dolor moderado o intenso. Puede crear dependencia."],
      steroid: ["Esteroide", "Reduce la hinchazón y calma el sistema inmunitario. Se usa para alergias, asma, artritis y problemas de la piel."],
      breathing: ["Medicamento para respirar", "Abre las vías respiratorias o reduce su hinchazón. Se usa para el asma, la EPOC o las alergias."],
      allergy: ["Antihistamínico", "Alivia síntomas de alergia como estornudos, goteo nasal, picazón y ronchas."],
      blood_thinner: ["Anticoagulante", "Previene coágulos de sangre peligrosos que pueden causar un derrame cerebral o bloquear los vasos sanguíneos."],
      antiplatelet: ["Antiagregante plaquetario", "Evita que las células de la sangre se agrupen, para ayudar a prevenir ataques al corazón y derrames cerebrales."],
      gout: ["Medicamento para la gota", "Previene o trata la gota, una hinchazón dolorosa de las articulaciones causada por el ácido úrico."],
      prostate: ["Medicamento para la próstata", "Alivia problemas para orinar causados por una próstata agrandada."],
      blood_flow: ["Medicamento para el flujo sanguíneo", "Mejora el flujo de sangre. Se usa para la disfunción eréctil o la presión alta en los pulmones."],
      hormone: ["Medicamento hormonal", "Se usa como anticonceptivo, para síntomas de la menopausia o problemas menstruales."],
      mood: ["Estabilizador del ánimo / antipsicótico", "Ayuda a estabilizar el ánimo y el pensamiento. Se usa para el trastorno bipolar, la esquizofrenia y a veces la depresión."],
      adhd: ["Medicamento para el TDAH (estimulante)", "Mejora la concentración y la atención. Puede crear dependencia."],
      memory: ["Medicamento para la memoria", "Ayuda a la memoria y al pensamiento en la enfermedad de Alzheimer."],
      parkinson: ["Medicamento para el Parkinson", "Trata la enfermedad de Parkinson y el síndrome de piernas inquietas."],
      migraine: ["Medicamento para la migraña", "Detiene una migraña después de que empieza."],
      supplement: ["Vitamina o mineral", "Repone una vitamina o un mineral que le falta a su cuerpo."],
      cough: ["Medicamento para la tos", "Calma la tos."],
      gut_cramps: ["Medicamento para cólicos estomacales", "Alivia los cólicos del estómago y el intestino, como los del síndrome del intestino irritable."],
      glaucoma: ["Medicamento para la presión del ojo", "Baja la presión dentro del ojo para tratar el glaucoma."],
      immune: ["Medicamento para el sistema inmunitario", "Calma un sistema inmunitario demasiado activo. Se usa para la artritis reumatoide, la psoriasis y algunos cánceres."],
    },
  },

  zh: {
    label: "用途",
    note: "医生可能出于其他原因为您开了这种药。如有疑问，请咨询医生。",
    classes: {
      antibiotic: ["抗生素", "杀死细菌，治疗感染。对感冒和流感无效。"],
      antiviral: ["抗病毒药", "对抗病毒，例如引起唇疱疹、带状疱疹或流感的病毒。"],
      antifungal: ["抗真菌药", "治疗真菌感染，例如酵母菌感染。"],
      blood_pressure: ["降压药", "降低血压，保护心脏、大脑和肾脏。"],
      heart_rate: ["β受体阻滞剂", "减慢心率并降低血压。用于高血压和心脏疾病。"],
      water_pill: ["利尿剂", "帮助身体排出多余的水和盐，减轻水肿并降低血压。"],
      cholesterol: ["降胆固醇药", "降低胆固醇，减少心脏病发作和中风的风险。"],
      diabetes: ["糖尿病药", "为糖尿病患者降低血糖。"],
      thyroid: ["甲状腺激素", "在甲状腺功能减退时补充甲状腺激素。"],
      stomach_acid: ["抑酸药", "减少胃酸，治疗烧心、胃酸反流和溃疡。"],
      nausea: ["止吐药", "预防或缓解恶心、呕吐或晕动病。"],
      antidepressant: ["抗抑郁药", "通过调节大脑中的化学物质来治疗抑郁和焦虑。"],
      anxiety: ["抗焦虑药", "减轻焦虑。"],
      sedative: ["镇静药", "缓解焦虑、惊恐或肌肉痉挛。可能会成瘾。"],
      sleep: ["助眠药", "帮助入睡并保持睡眠。"],
      nerve: ["抗癫痫及神经痛药", "让过度活跃的神经平静下来。用于癫痫发作和神经痛。"],
      muscle: ["肌肉松弛剂", "放松紧绷或抽筋的肌肉。"],
      pain_inflammation: ["消炎止痛药（NSAID）", "减轻疼痛、肿胀和发烧。"],
      pain_fever: ["止痛退烧药", "缓解疼痛并退烧。"],
      opioid: ["强效止痛药（阿片类）", "缓解中度至重度疼痛。可能会成瘾。"],
      steroid: ["类固醇", "减轻炎症并抑制免疫系统。用于过敏、哮喘、关节炎和皮肤问题。"],
      breathing: ["呼吸用药", "扩张气道或减轻气道肿胀。用于哮喘、慢阻肺或过敏。"],
      allergy: ["抗组胺药", "缓解过敏症状，如打喷嚏、流鼻涕、瘙痒和荨麻疹。"],
      blood_thinner: ["抗凝血药", "预防可能导致中风或堵塞血管的危险血栓。"],
      antiplatelet: ["抗血小板药", "防止血细胞聚集，帮助预防心脏病发作和中风。"],
      gout: ["痛风药", "预防或治疗痛风（由尿酸引起的关节疼痛肿胀）。"],
      prostate: ["前列腺用药", "缓解前列腺增大引起的排尿问题。"],
      blood_flow: ["改善血流的药", "改善血液流动。用于勃起功能障碍或肺动脉高压。"],
      hormone: ["激素类药物", "用于避孕、更年期症状或月经问题。"],
      mood: ["情绪稳定剂／抗精神病药", "帮助稳定情绪和思维。用于双相情感障碍、精神分裂症，有时也用于抑郁症。"],
      adhd: ["多动症药（兴奋剂）", "改善专注力和注意力。可能会成瘾。"],
      memory: ["改善记忆的药", "帮助阿尔茨海默病患者的记忆和思考能力。"],
      parkinson: ["帕金森病药", "治疗帕金森病和不宁腿综合征。"],
      migraine: ["偏头痛药", "在偏头痛发作后止住头痛。"],
      supplement: ["维生素或矿物质", "补充身体缺乏的维生素或矿物质。"],
      cough: ["止咳药", "缓解咳嗽。"],
      gut_cramps: ["胃肠解痉药", "缓解胃部和肠道痉挛，例如肠易激综合征引起的痉挛。"],
      glaucoma: ["降眼压药", "降低眼内压力，治疗青光眼。"],
      immune: ["免疫系统用药", "抑制过度活跃的免疫系统。用于类风湿关节炎、银屑病和某些癌症。"],
    },
  },

  hi: {
    label: "यह दवा किस लिए है",
    note: "हो सकता है डॉक्टर ने इसे किसी और कारण से दिया हो। अगर पक्का न हो तो पूछें।",
    classes: {
      antibiotic: ["एंटीबायोटिक", "बैक्टीरिया को मारकर संक्रमण का इलाज करती है। सर्दी-जुकाम या फ्लू पर काम नहीं करती।"],
      antiviral: ["एंटीवायरल", "वायरस से लड़ती है, जैसे होंठों के छाले, दाद (शिंगल्स) या फ्लू के वायरस।"],
      antifungal: ["एंटीफंगल", "फंगल संक्रमण का इलाज करती है, जैसे यीस्ट संक्रमण।"],
      blood_pressure: ["ब्लड प्रेशर की दवा", "ब्लड प्रेशर कम करती है ताकि दिल, दिमाग और किडनी सुरक्षित रहें।"],
      heart_rate: ["बीटा ब्लॉकर", "दिल की धड़कन धीमी करती है और ब्लड प्रेशर कम करती है। हाई ब्लड प्रेशर और दिल की बीमारियों में दी जाती है।"],
      water_pill: ["पेशाब बढ़ाने वाली दवा (डाययूरेटिक)", "शरीर से अतिरिक्त पानी और नमक निकालने में मदद करती है, जिससे सूजन और ब्लड प्रेशर कम होते हैं।"],
      cholesterol: ["कोलेस्ट्रॉल की दवा", "कोलेस्ट्रॉल कम करती है ताकि हार्ट अटैक और स्ट्रोक का खतरा घटे।"],
      diabetes: ["डायबिटीज़ की दवा", "डायबिटीज़ वाले लोगों में ब्लड शुगर कम करती है।"],
      thyroid: ["थायरॉइड हार्मोन", "थायरॉइड कम काम करने पर थायरॉइड हार्मोन की कमी पूरी करती है।"],
      stomach_acid: ["पेट का एसिड कम करने वाली दवा", "पेट का एसिड कम करती है। सीने में जलन, एसिड रिफ्लक्स और अल्सर का इलाज करती है।"],
      nausea: ["मतली रोकने की दवा", "मतली, उल्टी या सफ़र में चक्कर को रोकती या कम करती है।"],
      antidepressant: ["एंटीडिप्रेसेंट", "दिमाग के रसायनों को संतुलित करके डिप्रेशन और चिंता का इलाज करती है।"],
      anxiety: ["चिंता की दवा", "चिंता कम करती है।"],
      sedative: ["शांत करने वाली दवा (सेडेटिव)", "चिंता, घबराहट या मांसपेशियों की ऐंठन को शांत करती है। इसकी आदत पड़ सकती है।"],
      sleep: ["नींद की दवा", "सोने और सोते रहने में मदद करती है।"],
      nerve: ["दौरे और नसों के दर्द की दवा", "ज़्यादा सक्रिय नसों को शांत करती है। दौरे और नसों के दर्द में दी जाती है।"],
      muscle: ["मांसपेशियों को ढीला करने वाली दवा", "अकड़ी हुई या ऐंठती मांसपेशियों को आराम देती है।"],
      pain_inflammation: ["दर्द और सूजन की दवा (NSAID)", "दर्द, सूजन और बुखार कम करती है।"],
      pain_fever: ["दर्द और बुखार की दवा", "दर्द से राहत देती है और बुखार कम करती है।"],
      opioid: ["तेज़ दर्द निवारक (ओपिओइड)", "मध्यम से तेज़ दर्द से राहत देती है। इसकी आदत पड़ सकती है।"],
      steroid: ["स्टेरॉयड", "सूजन कम करती है और प्रतिरक्षा प्रणाली को शांत करती है। एलर्जी, अस्थमा, गठिया और त्वचा की समस्याओं में दी जाती है।"],
      breathing: ["साँस की दवा", "साँस की नलियों को खोलती है या उनकी सूजन कम करती है। अस्थमा, COPD या एलर्जी में दी जाती है।"],
      allergy: ["एंटीहिस्टामाइन", "छींक, नाक बहना, खुजली और पित्ती जैसे एलर्जी के लक्षणों से राहत देती है।"],
      blood_thinner: ["खून पतला करने की दवा", "खतरनाक खून के थक्कों को बनने से रोकती है जो स्ट्रोक कर सकते हैं या नसें बंद कर सकते हैं।"],
      antiplatelet: ["थक्का रोकने वाली दवा", "खून की कोशिकाओं को आपस में चिपकने से रोकती है, जिससे हार्ट अटैक और स्ट्रोक से बचाव होता है।"],
      gout: ["गाउट की दवा", "गाउट को रोकती या उसका इलाज करती है, जो यूरिक एसिड से जोड़ों में होने वाली दर्दभरी सूजन है।"],
      prostate: ["प्रोस्टेट की दवा", "बढ़े हुए प्रोस्टेट से होने वाली पेशाब की परेशानी को कम करती है।"],
      blood_flow: ["खून का बहाव बढ़ाने वाली दवा", "खून का बहाव बेहतर करती है। स्तंभन दोष (ED) या फेफड़ों के हाई ब्लड प्रेशर में दी जाती है।"],
      hormone: ["हार्मोन की दवा", "गर्भनिरोध, मेनोपॉज़ के लक्षणों या माहवारी की समस्याओं के लिए दी जाती है।"],
      mood: ["मूड स्थिर करने वाली / एंटीसाइकोटिक दवा", "मूड और सोच को स्थिर रखने में मदद करती है। बाइपोलर डिसऑर्डर, सिज़ोफ्रेनिया और कभी-कभी डिप्रेशन में दी जाती है।"],
      adhd: ["ADHD की दवा (स्टिमुलेंट)", "ध्यान और एकाग्रता बढ़ाती है। इसकी आदत पड़ सकती है।"],
      memory: ["याददाश्त की दवा", "अल्ज़ाइमर रोग में याददाश्त और सोचने की क्षमता में मदद करती है।"],
      parkinson: ["पार्किंसंस की दवा", "पार्किंसंस रोग और रेस्टलेस लेग्स सिंड्रोम का इलाज करती है।"],
      migraine: ["माइग्रेन की दवा", "माइग्रेन शुरू होने के बाद उसे रोकती है।"],
      supplement: ["विटामिन या खनिज", "शरीर में किसी विटामिन या खनिज की कमी पूरी करती है।"],
      cough: ["खाँसी की दवा", "खाँसी को शांत करती है।"],
      gut_cramps: ["पेट की ऐंठन की दवा", "पेट और आँतों की ऐंठन से राहत देती है, जैसे इर्रिटेबल बाउल सिंड्रोम में।"],
      glaucoma: ["आँख के दबाव की दवा", "आँख के अंदर का दबाव कम करके ग्लूकोमा का इलाज करती है।"],
      immune: ["प्रतिरक्षा प्रणाली की दवा", "ज़्यादा सक्रिय प्रतिरक्षा प्रणाली को शांत करती है। रूमेटॉइड आर्थराइटिस, सोरायसिस और कुछ कैंसर में दी जाती है।"],
    },
  },

  te: {
    label: "ఈ మందు దేనికి",
    note: "డాక్టర్ దీన్ని వేరే కారణంతో ఇచ్చి ఉండవచ్చు. సందేహం ఉంటే అడగండి.",
    classes: {
      antibiotic: ["యాంటీబయాటిక్", "బ్యాక్టీరియాను చంపి ఇన్ఫెక్షన్లను నయం చేస్తుంది. జలుబు లేదా ఫ్లూకు పని చేయదు."],
      antiviral: ["యాంటీవైరల్", "పెదవులపై పుండ్లు, షింగిల్స్ లేదా ఫ్లూ కలిగించే వైరస్‌లతో పోరాడుతుంది."],
      antifungal: ["యాంటీఫంగల్", "ఈస్ట్ ఇన్ఫెక్షన్ వంటి ఫంగల్ ఇన్ఫెక్షన్లను నయం చేస్తుంది."],
      blood_pressure: ["బీపీ మందు", "రక్తపోటును తగ్గించి గుండె, మెదడు, కిడ్నీలను కాపాడుతుంది."],
      heart_rate: ["బీటా బ్లాకర్", "గుండె కొట్టుకోవడాన్ని నెమ్మదిస్తుంది, రక్తపోటును తగ్గిస్తుంది. అధిక బీపీ, గుండె సమస్యలకు వాడతారు."],
      water_pill: ["మూత్రవర్ధక మందు (డైయూరెటిక్)", "శరీరంలోని అదనపు నీరు, ఉప్పును బయటకు పంపి వాపు, బీపీని తగ్గిస్తుంది."],
      cholesterol: ["కొలెస్ట్రాల్ మందు", "కొలెస్ట్రాల్‌ను తగ్గించి గుండెపోటు, పక్షవాతం ప్రమాదాన్ని తగ్గిస్తుంది."],
      diabetes: ["షుగర్ (డయాబెటిస్) మందు", "డయాబెటిస్ ఉన్నవారిలో రక్తంలో చక్కెరను తగ్గిస్తుంది."],
      thyroid: ["థైరాయిడ్ హార్మోన్", "థైరాయిడ్ తక్కువగా పనిచేసినప్పుడు థైరాయిడ్ హార్మోన్‌ను భర్తీ చేస్తుంది."],
      stomach_acid: ["కడుపు ఆమ్లం తగ్గించే మందు", "కడుపులో ఆమ్లాన్ని తగ్గించి గుండెల్లో మంట, ఎసిడ్ రిఫ్లక్స్, అల్సర్లను నయం చేస్తుంది."],
      nausea: ["వికారం తగ్గించే మందు", "వికారం, వాంతులు లేదా ప్రయాణంలో కళ్ళు తిరగడాన్ని నివారిస్తుంది లేదా తగ్గిస్తుంది."],
      antidepressant: ["యాంటీడిప్రెసెంట్", "మెదడులోని రసాయనాలను సమతుల్యం చేసి డిప్రెషన్, ఆందోళనను నయం చేస్తుంది."],
      anxiety: ["ఆందోళన తగ్గించే మందు", "ఆందోళనను తగ్గిస్తుంది."],
      sedative: ["ప్రశాంతపరిచే మందు (సెడేటివ్)", "ఆందోళన, భయాందోళన లేదా కండరాల నొప్పులను తగ్గిస్తుంది. అలవాటు కావచ్చు."],
      sleep: ["నిద్ర మందు", "నిద్ర పట్టడానికి, నిద్ర కొనసాగడానికి సహాయపడుతుంది."],
      nerve: ["మూర్ఛ, నరాల నొప్పి మందు", "అతిగా పనిచేసే నరాలను శాంతపరుస్తుంది. మూర్ఛలు, నరాల నొప్పికి వాడతారు."],
      muscle: ["కండరాలను సడలించే మందు", "బిగుసుకున్న లేదా పట్టేసిన కండరాలను సడలిస్తుంది."],
      pain_inflammation: ["నొప్పి, వాపు మందు (NSAID)", "నొప్పి, వాపు, జ్వరాన్ని తగ్గిస్తుంది."],
      pain_fever: ["నొప్పి, జ్వరం మందు", "నొప్పిని, జ్వరాన్ని తగ్గిస్తుంది."],
      opioid: ["బలమైన నొప్పి మందు (ఓపియాయిడ్)", "మధ్యస్థం నుండి తీవ్రమైన నొప్పిని తగ్గిస్తుంది. అలవాటు కావచ్చు."],
      steroid: ["స్టెరాయిడ్", "వాపును తగ్గించి రోగనిరోధక వ్యవస్థను శాంతపరుస్తుంది. అలెర్జీలు, ఆస్తమా, కీళ్లవాతం, చర్మ సమస్యలకు వాడతారు."],
      breathing: ["శ్వాస మందు", "శ్వాస మార్గాలను తెరుస్తుంది లేదా వాటి వాపును తగ్గిస్తుంది. ఆస్తమా, COPD లేదా అలెర్జీలకు వాడతారు."],
      allergy: ["యాంటీహిస్టమైన్", "తుమ్ములు, ముక్కు కారడం, దురద, దద్దుర్లు వంటి అలెర్జీ లక్షణాలను తగ్గిస్తుంది."],
      blood_thinner: ["రక్తం పలచబరిచే మందు", "పక్షవాతం కలిగించే లేదా రక్తనాళాలను అడ్డుకునే ప్రమాదకర రక్తం గడ్డలను నివారిస్తుంది."],
      antiplatelet: ["రక్తం గడ్డకట్టకుండా చేసే మందు", "రక్తకణాలు ఒకదానికొకటి అతుక్కోకుండా చేసి గుండెపోటు, పక్షవాతాన్ని నివారించడంలో సహాయపడుతుంది."],
      gout: ["గౌట్ మందు", "యూరిక్ ఆమ్లం వల్ల కీళ్లలో వచ్చే బాధాకరమైన వాపు అయిన గౌట్‌ను నివారిస్తుంది లేదా నయం చేస్తుంది."],
      prostate: ["ప్రోస్టేట్ మందు", "పెరిగిన ప్రోస్టేట్ వల్ల వచ్చే మూత్ర సమస్యలను తగ్గిస్తుంది."],
      blood_flow: ["రక్త ప్రసరణ మందు", "రక్త ప్రసరణను మెరుగుపరుస్తుంది. అంగస్తంభన సమస్య లేదా ఊపిరితిత్తుల్లో అధిక రక్తపోటుకు వాడతారు."],
      hormone: ["హార్మోన్ మందు", "గర్భనిరోధకంగా, మెనోపాజ్ లక్షణాలకు లేదా నెలసరి సమస్యలకు వాడతారు."],
      mood: ["మూడ్ స్టెబిలైజర్ / యాంటీసైకోటిక్", "మనస్థితి, ఆలోచనలను స్థిరంగా ఉంచడంలో సహాయపడుతుంది. బైపోలార్ డిజార్డర్, స్కిజోఫ్రేనియా, కొన్నిసార్లు డిప్రెషన్‌కు వాడతారు."],
      adhd: ["ADHD మందు (స్టిమ్యులెంట్)", "ఏకాగ్రత, శ్రద్ధను మెరుగుపరుస్తుంది. అలవాటు కావచ్చు."],
      memory: ["జ్ఞాపకశక్తి మందు", "అల్జీమర్స్ వ్యాధిలో జ్ఞాపకశక్తి, ఆలోచనకు సహాయపడుతుంది."],
      parkinson: ["పార్కిన్సన్స్ మందు", "పార్కిన్సన్స్ వ్యాధి, రెస్ట్‌లెస్ లెగ్స్ సిండ్రోమ్‌ను నయం చేస్తుంది."],
      migraine: ["మైగ్రేన్ మందు", "మైగ్రేన్ తలనొప్పి మొదలైన తర్వాత దాన్ని ఆపుతుంది."],
      supplement: ["విటమిన్ లేదా ఖనిజం", "శరీరంలో తక్కువగా ఉన్న విటమిన్ లేదా ఖనిజాన్ని భర్తీ చేస్తుంది."],
      cough: ["దగ్గు మందు", "దగ్గును తగ్గిస్తుంది."],
      gut_cramps: ["కడుపు నొప్పి (ఈడ్పు) మందు", "ఇరిటబుల్ బవెల్ సిండ్రోమ్ వంటి వాటి వల్ల కడుపు, పేగుల్లో వచ్చే ఈడ్పులను తగ్గిస్తుంది."],
      glaucoma: ["కంటి ఒత్తిడి మందు", "కంటి లోపలి ఒత్తిడిని తగ్గించి గ్లాకోమాను నయం చేస్తుంది."],
      immune: ["రోగనిరోధక వ్యవస్థ మందు", "అతిగా పనిచేసే రోగనిరోధక వ్యవస్థను శాంతపరుస్తుంది. రుమటాయిడ్ ఆర్థరైటిస్, సోరియాసిస్, కొన్ని క్యాన్సర్లకు వాడతారు."],
    },
  },

  ar: {
    label: "لماذا يُستخدم هذا الدواء",
    note: "ربما وصفه الطبيب لسبب آخر. اسأل إذا لم تكن متأكدًا.",
    classes: {
      antibiotic: ["مضاد حيوي", "يقتل البكتيريا لعلاج العدوى. لا يفيد في نزلات البرد أو الإنفلونزا."],
      antiviral: ["مضاد للفيروسات", "يحارب الفيروسات، مثل التي تسبب قروح البرد أو الحزام الناري أو الإنفلونزا."],
      antifungal: ["مضاد للفطريات", "يعالج العدوى الفطرية، مثل عدوى الخميرة."],
      blood_pressure: ["دواء ضغط الدم", "يخفض ضغط الدم لحماية القلب والدماغ والكليتين."],
      heart_rate: ["حاصر بيتا", "يبطئ ضربات القلب ويخفض ضغط الدم. يُستخدم لارتفاع الضغط وأمراض القلب."],
      water_pill: ["مدر للبول", "يساعد الجسم على التخلص من الماء والملح الزائدين، فيقلل التورم وضغط الدم."],
      cholesterol: ["دواء الكوليسترول", "يخفض الكوليسترول لتقليل خطر النوبة القلبية والسكتة الدماغية."],
      diabetes: ["دواء السكري", "يخفض سكر الدم لدى مرضى السكري."],
      thyroid: ["هرمون الغدة الدرقية", "يعوّض هرمون الغدة الدرقية عندما تكون الغدة خاملة."],
      stomach_acid: ["مخفض حموضة المعدة", "يقلل حمض المعدة لعلاج الحرقة وارتجاع الحمض والقرحة."],
      nausea: ["دواء مضاد للغثيان", "يمنع أو يخفف الغثيان والقيء ودوار الحركة."],
      antidepressant: ["مضاد للاكتئاب", "يعالج الاكتئاب والقلق بموازنة المواد الكيميائية في الدماغ."],
      anxiety: ["دواء القلق", "يخفف القلق."],
      sedative: ["مهدئ", "يهدئ القلق أو نوبات الهلع أو تشنجات العضلات. قد يسبب الإدمان."],
      sleep: ["دواء النوم", "يساعدك على النوم والاستمرار فيه."],
      nerve: ["دواء للتشنجات وألم الأعصاب", "يهدئ الأعصاب شديدة النشاط. يُستخدم للنوبات التشنجية وألم الأعصاب."],
      muscle: ["مرخٍ للعضلات", "يرخي العضلات المشدودة أو المتشنجة."],
      pain_inflammation: ["مسكن ومضاد للالتهاب", "يخفف الألم والتورم والحمى."],
      pain_fever: ["مسكن وخافض للحرارة", "يخفف الألم ويخفض الحرارة."],
      opioid: ["مسكن قوي (أفيوني)", "يخفف الألم المتوسط إلى الشديد. قد يسبب الإدمان."],
      steroid: ["ستيرويد", "يقلل الالتهاب ويهدئ جهاز المناعة. يُستخدم للحساسية والربو والتهاب المفاصل ومشاكل الجلد."],
      breathing: ["دواء للتنفس", "يفتح مجاري التنفس أو يقلل تورمها. يُستخدم للربو أو مرض الانسداد الرئوي المزمن أو الحساسية."],
      allergy: ["مضاد للهيستامين", "يخفف أعراض الحساسية مثل العطس وسيلان الأنف والحكة والشرى."],
      blood_thinner: ["مميّع للدم", "يمنع الجلطات الدموية الخطيرة التي قد تسبب سكتة دماغية أو تسد الأوعية الدموية."],
      antiplatelet: ["مضاد للصفائح الدموية", "يمنع خلايا الدم من التكتل، للمساعدة في الوقاية من النوبة القلبية والسكتة الدماغية."],
      gout: ["دواء النقرس", "يمنع أو يعالج النقرس، وهو تورم مؤلم في المفاصل بسبب حمض اليوريك."],
      prostate: ["دواء البروستاتا", "يخفف مشاكل التبول الناتجة عن تضخم البروستاتا."],
      blood_flow: ["دواء لتحسين تدفق الدم", "يحسن تدفق الدم. يُستخدم لضعف الانتصاب أو ارتفاع ضغط الدم الرئوي."],
      hormone: ["دواء هرموني", "يُستخدم لمنع الحمل أو لأعراض انقطاع الطمث أو مشاكل الدورة الشهرية."],
      mood: ["مثبت للمزاج / مضاد للذهان", "يساعد على استقرار المزاج والتفكير. يُستخدم للاضطراب ثنائي القطب والفصام وأحيانًا الاكتئاب."],
      adhd: ["دواء فرط الحركة ونقص الانتباه (منشط)", "يحسن التركيز والانتباه. قد يسبب الإدمان."],
      memory: ["دواء للذاكرة", "يساعد الذاكرة والتفكير لدى مرضى ألزهايمر."],
      parkinson: ["دواء باركنسون", "يعالج مرض باركنسون ومتلازمة تململ الساقين."],
      migraine: ["دواء الصداع النصفي", "يوقف نوبة الصداع النصفي بعد أن تبدأ."],
      supplement: ["فيتامين أو معدن", "يعوّض فيتامينًا أو معدنًا ينقص جسمك."],
      cough: ["دواء السعال", "يهدئ السعال."],
      gut_cramps: ["دواء تقلصات المعدة", "يخفف تقلصات المعدة والأمعاء، مثل تلك الناتجة عن متلازمة القولون العصبي."],
      glaucoma: ["دواء ضغط العين", "يخفض الضغط داخل العين لعلاج الجلوكوما (الزرق)."],
      immune: ["دواء لجهاز المناعة", "يهدئ جهاز المناعة شديد النشاط. يُستخدم لالتهاب المفاصل الروماتويدي والصدفية وبعض أنواع السرطان."],
    },
  },

  vi: {
    label: "Thuốc dùng để làm gì",
    note: "Bác sĩ có thể kê thuốc này vì lý do khác. Hãy hỏi nếu bạn không chắc.",
    classes: {
      antibiotic: ["Thuốc kháng sinh", "Diệt vi khuẩn để chữa nhiễm trùng. Không có tác dụng với cảm lạnh hay cúm."],
      antiviral: ["Thuốc kháng vi-rút", "Chống lại vi-rút, như loại gây mụn rộp môi, zona hoặc cúm."],
      antifungal: ["Thuốc kháng nấm", "Chữa nhiễm nấm, như nhiễm nấm men."],
      blood_pressure: ["Thuốc huyết áp", "Hạ huyết áp để bảo vệ tim, não và thận."],
      heart_rate: ["Thuốc chẹn beta", "Làm tim đập chậm lại và hạ huyết áp. Dùng cho bệnh cao huyết áp và bệnh tim."],
      water_pill: ["Thuốc lợi tiểu", "Giúp cơ thể thải bớt nước và muối thừa, giảm phù và hạ huyết áp."],
      cholesterol: ["Thuốc mỡ máu", "Hạ cholesterol để giảm nguy cơ đau tim và đột quỵ."],
      diabetes: ["Thuốc tiểu đường", "Hạ đường huyết ở người bị tiểu đường."],
      thyroid: ["Hormone tuyến giáp", "Bổ sung hormone tuyến giáp khi tuyến giáp hoạt động kém."],
      stomach_acid: ["Thuốc giảm axit dạ dày", "Giảm axit dạ dày để chữa ợ nóng, trào ngược axit và loét."],
      nausea: ["Thuốc chống buồn nôn", "Ngừa hoặc giảm buồn nôn, nôn hoặc say tàu xe."],
      antidepressant: ["Thuốc chống trầm cảm", "Chữa trầm cảm và lo âu bằng cách cân bằng các chất hóa học trong não."],
      anxiety: ["Thuốc chống lo âu", "Giảm lo âu."],
      sedative: ["Thuốc an thần", "Làm dịu lo âu, hoảng sợ hoặc co thắt cơ. Có thể gây nghiện."],
      sleep: ["Thuốc ngủ", "Giúp bạn dễ ngủ và ngủ không bị thức giấc."],
      nerve: ["Thuốc chống co giật và đau thần kinh", "Làm dịu các dây thần kinh hoạt động quá mức. Dùng cho co giật và đau thần kinh."],
      muscle: ["Thuốc giãn cơ", "Làm giãn các cơ bị căng hoặc chuột rút."],
      pain_inflammation: ["Thuốc giảm đau chống viêm (NSAID)", "Giảm đau, sưng và sốt."],
      pain_fever: ["Thuốc giảm đau hạ sốt", "Giảm đau và hạ sốt."],
      opioid: ["Thuốc giảm đau mạnh (opioid)", "Giảm đau vừa đến nặng. Có thể gây nghiện."],
      steroid: ["Thuốc steroid", "Giảm viêm và làm dịu hệ miễn dịch. Dùng cho dị ứng, hen suyễn, viêm khớp và bệnh ngoài da."],
      breathing: ["Thuốc hô hấp", "Làm thông đường thở hoặc giảm sưng đường thở. Dùng cho hen suyễn, bệnh phổi tắc nghẽn mãn tính (COPD) hoặc dị ứng."],
      allergy: ["Thuốc kháng histamin", "Giảm triệu chứng dị ứng như hắt hơi, sổ mũi, ngứa và nổi mề đay."],
      blood_thinner: ["Thuốc chống đông máu", "Ngừa cục máu đông nguy hiểm có thể gây đột quỵ hoặc làm tắc mạch máu."],
      antiplatelet: ["Thuốc chống kết tập tiểu cầu", "Giữ cho tế bào máu không kết dính lại, giúp ngừa đau tim và đột quỵ."],
      gout: ["Thuốc bệnh gút", "Ngừa hoặc chữa bệnh gút, tình trạng sưng đau khớp do axit uric."],
      prostate: ["Thuốc tuyến tiền liệt", "Giảm khó khăn khi đi tiểu do phì đại tuyến tiền liệt."],
      blood_flow: ["Thuốc tăng lưu thông máu", "Cải thiện lưu thông máu. Dùng cho rối loạn cương dương hoặc tăng áp động mạch phổi."],
      hormone: ["Thuốc nội tiết tố", "Dùng để tránh thai, giảm triệu chứng mãn kinh hoặc chữa các vấn đề kinh nguyệt."],
      mood: ["Thuốc ổn định tâm trạng / chống loạn thần", "Giúp ổn định tâm trạng và suy nghĩ. Dùng cho rối loạn lưỡng cực, tâm thần phân liệt và đôi khi trầm cảm."],
      adhd: ["Thuốc ADHD (chất kích thích)", "Cải thiện sự tập trung và chú ý. Có thể gây nghiện."],
      memory: ["Thuốc trí nhớ", "Hỗ trợ trí nhớ và suy nghĩ ở người bị bệnh Alzheimer."],
      parkinson: ["Thuốc bệnh Parkinson", "Chữa bệnh Parkinson và hội chứng chân không yên."],
      migraine: ["Thuốc đau nửa đầu", "Cắt cơn đau nửa đầu sau khi cơn đau bắt đầu."],
      supplement: ["Vitamin hoặc khoáng chất", "Bổ sung vitamin hoặc khoáng chất mà cơ thể đang thiếu."],
      cough: ["Thuốc ho", "Làm dịu cơn ho."],
      gut_cramps: ["Thuốc chống co thắt dạ dày", "Giảm co thắt dạ dày và ruột, như trong hội chứng ruột kích thích."],
      glaucoma: ["Thuốc nhãn áp", "Hạ áp lực bên trong mắt để chữa bệnh tăng nhãn áp (glôcôm)."],
      immune: ["Thuốc hệ miễn dịch", "Làm dịu hệ miễn dịch hoạt động quá mức. Dùng cho viêm khớp dạng thấp, vảy nến và một số bệnh ung thư."],
    },
  },

  ko: {
    label: "이 약의 용도",
    note: "의사가 다른 이유로 처방했을 수도 있습니다. 확실하지 않으면 물어보세요.",
    classes: {
      antibiotic: ["항생제", "세균을 죽여 감염을 치료합니다. 감기나 독감에는 효과가 없습니다."],
      antiviral: ["항바이러스제", "입술 물집, 대상포진, 독감 등을 일으키는 바이러스와 싸웁니다."],
      antifungal: ["항진균제", "칸디다 감염 같은 곰팡이 감염을 치료합니다."],
      blood_pressure: ["혈압약", "혈압을 낮춰 심장, 뇌, 신장을 보호합니다."],
      heart_rate: ["베타 차단제", "심장 박동을 느리게 하고 혈압을 낮춥니다. 고혈압과 심장 질환에 사용합니다."],
      water_pill: ["이뇨제", "몸에서 남는 수분과 소금을 빼내 부기와 혈압을 줄입니다."],
      cholesterol: ["콜레스테롤 약", "콜레스테롤을 낮춰 심장마비와 뇌졸중 위험을 줄입니다."],
      diabetes: ["당뇨약", "당뇨병 환자의 혈당을 낮춥니다."],
      thyroid: ["갑상선 호르몬", "갑상선 기능이 떨어졌을 때 갑상선 호르몬을 보충합니다."],
      stomach_acid: ["위산 억제제", "위산을 줄여 속쓰림, 위산 역류, 궤양을 치료합니다."],
      nausea: ["구토 억제제", "메스꺼움, 구토, 멀미를 예방하거나 완화합니다."],
      antidepressant: ["항우울제", "뇌의 화학 물질 균형을 맞춰 우울증과 불안을 치료합니다."],
      anxiety: ["항불안제", "불안을 줄여 줍니다."],
      sedative: ["진정제", "불안, 공황, 근육 경련을 진정시킵니다. 습관성이 생길 수 있습니다."],
      sleep: ["수면제", "잠들고 계속 잠을 자도록 도와줍니다."],
      nerve: ["발작 및 신경통 약", "과도하게 활동하는 신경을 진정시킵니다. 발작과 신경통에 사용합니다."],
      muscle: ["근육 이완제", "뭉치거나 쥐가 난 근육을 풀어 줍니다."],
      pain_inflammation: ["소염진통제(NSAID)", "통증, 부기, 열을 줄여 줍니다."],
      pain_fever: ["진통해열제", "통증을 덜고 열을 내립니다."],
      opioid: ["강한 진통제(마약성)", "중간에서 심한 통증을 덜어 줍니다. 습관성이 생길 수 있습니다."],
      steroid: ["스테로이드", "염증을 줄이고 면역 체계를 진정시킵니다. 알레르기, 천식, 관절염, 피부 질환에 사용합니다."],
      breathing: ["호흡기 약", "기도를 넓히거나 기도의 부기를 줄입니다. 천식, 만성폐쇄성폐질환(COPD), 알레르기에 사용합니다."],
      allergy: ["항히스타민제", "재채기, 콧물, 가려움, 두드러기 같은 알레르기 증상을 완화합니다."],
      blood_thinner: ["항응고제", "뇌졸중을 일으키거나 혈관을 막을 수 있는 위험한 혈전을 예방합니다."],
      antiplatelet: ["항혈소판제", "혈액 세포가 뭉치지 않게 하여 심장마비와 뇌졸중 예방을 돕습니다."],
      gout: ["통풍약", "요산 때문에 관절이 붓고 아픈 통풍을 예방하거나 치료합니다."],
      prostate: ["전립선 약", "커진 전립선 때문에 생기는 배뇨 문제를 완화합니다."],
      blood_flow: ["혈류 개선제", "혈액 순환을 좋게 합니다. 발기부전이나 폐동맥 고혈압에 사용합니다."],
      hormone: ["호르몬제", "피임, 폐경 증상, 생리 문제에 사용합니다."],
      mood: ["기분 안정제 / 항정신병약", "기분과 생각을 안정시키는 데 도움을 줍니다. 양극성 장애, 조현병, 때로는 우울증에 사용합니다."],
      adhd: ["ADHD 약(각성제)", "집중력과 주의력을 높여 줍니다. 습관성이 생길 수 있습니다."],
      memory: ["기억력 약", "알츠하이머병에서 기억력과 사고력을 돕습니다."],
      parkinson: ["파킨슨병 약", "파킨슨병과 하지불안증후군을 치료합니다."],
      migraine: ["편두통 약", "편두통이 시작된 후 멈추게 합니다."],
      supplement: ["비타민 또는 미네랄", "몸에 부족한 비타민이나 미네랄을 보충합니다."],
      cough: ["기침약", "기침을 진정시킵니다."],
      gut_cramps: ["복부 경련 약", "과민성 대장 증후군 등으로 인한 위와 장의 경련을 완화합니다."],
      glaucoma: ["안압 약", "눈 안의 압력을 낮춰 녹내장을 치료합니다."],
      immune: ["면역 억제제", "지나치게 활발한 면역 체계를 진정시킵니다. 류마티스 관절염, 건선, 일부 암에 사용합니다."],
    },
  },

  fr: {
    label: "À quoi ça sert",
    note: "Votre médecin l’a peut-être prescrit pour une autre raison. Demandez-lui en cas de doute.",
    classes: {
      antibiotic: ["Antibiotique", "Tue les bactéries pour traiter les infections. Ne marche pas contre le rhume ni la grippe."],
      antiviral: ["Antiviral", "Combat les virus, comme ceux du bouton de fièvre, du zona ou de la grippe."],
      antifungal: ["Antifongique", "Traite les infections par champignons, comme les mycoses."],
      blood_pressure: ["Médicament contre l’hypertension", "Fait baisser la tension artérielle pour protéger le cœur, le cerveau et les reins."],
      heart_rate: ["Bêtabloquant", "Ralentit le cœur et fait baisser la tension. Utilisé pour l’hypertension et les maladies du cœur."],
      water_pill: ["Diurétique", "Aide le corps à éliminer l’excès d’eau et de sel, ce qui réduit l’enflure et la tension."],
      cholesterol: ["Médicament contre le cholestérol", "Fait baisser le cholestérol pour réduire le risque de crise cardiaque et d’AVC."],
      diabetes: ["Médicament contre le diabète", "Fait baisser le sucre dans le sang chez les personnes diabétiques."],
      thyroid: ["Hormone thyroïdienne", "Remplace l’hormone thyroïdienne quand la thyroïde ne fonctionne pas assez."],
      stomach_acid: ["Anti-acide", "Réduit l’acidité de l’estomac pour traiter les brûlures d’estomac, le reflux et les ulcères."],
      nausea: ["Médicament contre les nausées", "Prévient ou soulage les nausées, les vomissements ou le mal des transports."],
      antidepressant: ["Antidépresseur", "Traite la dépression et l’anxiété en équilibrant certaines substances du cerveau."],
      anxiety: ["Médicament contre l’anxiété", "Réduit l’anxiété."],
      sedative: ["Sédatif", "Calme l’anxiété, les crises de panique ou les spasmes musculaires. Peut créer une dépendance."],
      sleep: ["Somnifère", "Aide à s’endormir et à rester endormi."],
      nerve: ["Médicament contre l’épilepsie et les douleurs nerveuses", "Calme les nerfs trop actifs. Utilisé pour les crises d’épilepsie et les douleurs nerveuses."],
      muscle: ["Relaxant musculaire", "Détend les muscles contractés ou les crampes."],
      pain_inflammation: ["Anti-inflammatoire (AINS)", "Réduit la douleur, l’enflure et la fièvre."],
      pain_fever: ["Antidouleur et antifièvre", "Soulage la douleur et fait baisser la fièvre."],
      opioid: ["Antidouleur puissant (opioïde)", "Soulage les douleurs modérées à fortes. Peut créer une dépendance."],
      steroid: ["Corticoïde", "Réduit l’inflammation et calme le système immunitaire. Utilisé pour les allergies, l’asthme, l’arthrite et les problèmes de peau."],
      breathing: ["Médicament pour la respiration", "Ouvre les voies respiratoires ou réduit leur inflammation. Utilisé pour l’asthme, la BPCO ou les allergies."],
      allergy: ["Antihistaminique", "Soulage les symptômes d’allergie comme les éternuements, le nez qui coule, les démangeaisons et l’urticaire."],
      blood_thinner: ["Anticoagulant", "Empêche la formation de caillots dangereux qui peuvent causer un AVC ou boucher les vaisseaux."],
      antiplatelet: ["Antiplaquettaire", "Empêche les cellules du sang de s’agglutiner, pour aider à prévenir crise cardiaque et AVC."],
      gout: ["Médicament contre la goutte", "Prévient ou traite la goutte, une inflammation douloureuse des articulations due à l’acide urique."],
      prostate: ["Médicament pour la prostate", "Soulage les problèmes pour uriner dus à une prostate trop grosse."],
      blood_flow: ["Médicament pour la circulation", "Améliore la circulation du sang. Utilisé pour les troubles de l’érection ou l’hypertension pulmonaire."],
      hormone: ["Médicament hormonal", "Utilisé comme contraception, contre les symptômes de la ménopause ou les problèmes de règles."],
      mood: ["Régulateur de l’humeur / antipsychotique", "Aide à stabiliser l’humeur et la pensée. Utilisé pour le trouble bipolaire, la schizophrénie et parfois la dépression."],
      adhd: ["Médicament contre le TDAH (stimulant)", "Améliore la concentration et l’attention. Peut créer une dépendance."],
      memory: ["Médicament pour la mémoire", "Aide la mémoire et la réflexion dans la maladie d’Alzheimer."],
      parkinson: ["Médicament contre le Parkinson", "Traite la maladie de Parkinson et le syndrome des jambes sans repos."],
      migraine: ["Médicament contre la migraine", "Arrête une migraine une fois qu’elle a commencé."],
      supplement: ["Vitamine ou minéral", "Remplace une vitamine ou un minéral qui manque à votre corps."],
      cough: ["Médicament contre la toux", "Calme la toux."],
      gut_cramps: ["Médicament contre les crampes d’estomac", "Soulage les crampes de l’estomac et de l’intestin, par exemple dans le syndrome de l’intestin irritable."],
      glaucoma: ["Médicament pour la pression de l’œil", "Fait baisser la pression dans l’œil pour traiter le glaucome."],
      immune: ["Médicament du système immunitaire", "Calme un système immunitaire trop actif. Utilisé pour la polyarthrite rhumatoïde, le psoriasis et certains cancers."],
    },
  },

  pt: {
    label: "Para que serve",
    note: "Seu médico pode ter receitado por outro motivo. Pergunte se tiver dúvida.",
    classes: {
      antibiotic: ["Antibiótico", "Mata bactérias para tratar infecções. Não funciona para resfriado ou gripe."],
      antiviral: ["Antiviral", "Combate vírus, como os que causam herpes labial, herpes-zóster ou gripe."],
      antifungal: ["Antifúngico", "Trata infecções por fungos, como candidíase."],
      blood_pressure: ["Remédio para pressão", "Baixa a pressão arterial para proteger o coração, o cérebro e os rins."],
      heart_rate: ["Betabloqueador", "Deixa os batimentos do coração mais lentos e baixa a pressão. Usado para pressão alta e problemas do coração."],
      water_pill: ["Diurético", "Ajuda o corpo a eliminar o excesso de água e sal, o que reduz o inchaço e a pressão."],
      cholesterol: ["Remédio para colesterol", "Baixa o colesterol para reduzir o risco de infarto e derrame."],
      diabetes: ["Remédio para diabetes", "Baixa o açúcar no sangue em pessoas com diabetes."],
      thyroid: ["Hormônio da tireoide", "Repõe o hormônio da tireoide quando ela funciona pouco."],
      stomach_acid: ["Redutor de acidez", "Reduz o ácido do estômago para tratar azia, refluxo e úlceras."],
      nausea: ["Remédio contra enjoo", "Previne ou alivia enjoo, vômito ou enjoo de movimento."],
      antidepressant: ["Antidepressivo", "Trata depressão e ansiedade equilibrando substâncias químicas do cérebro."],
      anxiety: ["Remédio para ansiedade", "Reduz a ansiedade."],
      sedative: ["Calmante (sedativo)", "Acalma a ansiedade, o pânico ou espasmos musculares. Pode causar dependência."],
      sleep: ["Remédio para dormir", "Ajuda a pegar no sono e a continuar dormindo."],
      nerve: ["Remédio para convulsões e dor nos nervos", "Acalma nervos hiperativos. Usado para convulsões e dor nos nervos."],
      muscle: ["Relaxante muscular", "Relaxa músculos tensos ou com cãibras."],
      pain_inflammation: ["Anti-inflamatório (AINE)", "Reduz dor, inchaço e febre."],
      pain_fever: ["Analgésico e antitérmico", "Alivia a dor e baixa a febre."],
      opioid: ["Analgésico forte (opioide)", "Alivia dor moderada a forte. Pode causar dependência."],
      steroid: ["Corticoide", "Reduz a inflamação e acalma o sistema imunológico. Usado para alergias, asma, artrite e problemas de pele."],
      breathing: ["Remédio para respirar", "Abre as vias respiratórias ou reduz o inchaço nelas. Usado para asma, DPOC ou alergias."],
      allergy: ["Anti-histamínico", "Alivia sintomas de alergia como espirros, nariz escorrendo, coceira e urticária."],
      blood_thinner: ["Anticoagulante", "Previne coágulos perigosos que podem causar derrame ou entupir vasos sanguíneos."],
      antiplatelet: ["Antiplaquetário", "Impede que as células do sangue se grudem, ajudando a prevenir infarto e derrame."],
      gout: ["Remédio para gota", "Previne ou trata a gota, um inchaço doloroso nas articulações causado pelo ácido úrico."],
      prostate: ["Remédio para próstata", "Alivia problemas para urinar causados pela próstata aumentada."],
      blood_flow: ["Remédio para circulação", "Melhora o fluxo de sangue. Usado para disfunção erétil ou pressão alta nos pulmões."],
      hormone: ["Remédio hormonal", "Usado como anticoncepcional, para sintomas da menopausa ou problemas menstruais."],
      mood: ["Estabilizador de humor / antipsicótico", "Ajuda a estabilizar o humor e o pensamento. Usado para transtorno bipolar, esquizofrenia e às vezes depressão."],
      adhd: ["Remédio para TDAH (estimulante)", "Melhora o foco e a atenção. Pode causar dependência."],
      memory: ["Remédio para memória", "Ajuda a memória e o raciocínio na doença de Alzheimer."],
      parkinson: ["Remédio para Parkinson", "Trata a doença de Parkinson e a síndrome das pernas inquietas."],
      migraine: ["Remédio para enxaqueca", "Interrompe uma crise de enxaqueca depois que ela começa."],
      supplement: ["Vitamina ou mineral", "Repõe uma vitamina ou mineral que está em falta no seu corpo."],
      cough: ["Remédio para tosse", "Acalma a tosse."],
      gut_cramps: ["Remédio para cólica", "Alivia cólicas do estômago e do intestino, como na síndrome do intestino irritável."],
      glaucoma: ["Remédio para pressão do olho", "Baixa a pressão dentro do olho para tratar o glaucoma."],
      immune: ["Remédio para o sistema imunológico", "Acalma um sistema imunológico hiperativo. Usado para artrite reumatoide, psoríase e alguns tipos de câncer."],
    },
  },

  ru: {
    label: "Для чего это лекарство",
    note: "Врач мог назначить его по другой причине. Если не уверены, спросите.",
    classes: {
      antibiotic: ["Антибиотик", "Убивает бактерии и лечит инфекции. Не помогает от простуды и гриппа."],
      antiviral: ["Противовирусное", "Борется с вирусами, например с герпесом, опоясывающим лишаём или гриппом."],
      antifungal: ["Противогрибковое", "Лечит грибковые инфекции, например молочницу."],
      blood_pressure: ["Лекарство от давления", "Снижает артериальное давление, защищая сердце, мозг и почки."],
      heart_rate: ["Бета-блокатор", "Замедляет сердцебиение и снижает давление. Применяется при повышенном давлении и болезнях сердца."],
      water_pill: ["Мочегонное", "Помогает организму выводить лишнюю воду и соль, уменьшая отёки и давление."],
      cholesterol: ["Лекарство от холестерина", "Снижает холестерин и риск инфаркта и инсульта."],
      diabetes: ["Лекарство от диабета", "Снижает сахар в крови при диабете."],
      thyroid: ["Гормон щитовидной железы", "Восполняет гормон щитовидной железы, когда она работает слабо."],
      stomach_acid: ["Средство от кислотности", "Уменьшает кислоту в желудке. Лечит изжогу, рефлюкс и язвы."],
      nausea: ["Средство от тошноты", "Предотвращает или облегчает тошноту, рвоту и укачивание."],
      antidepressant: ["Антидепрессант", "Лечит депрессию и тревогу, уравновешивая вещества в мозге."],
      anxiety: ["Средство от тревоги", "Уменьшает тревогу."],
      sedative: ["Успокоительное (седативное)", "Снимает тревогу, панику или мышечные спазмы. Может вызывать привыкание."],
      sleep: ["Снотворное", "Помогает заснуть и не просыпаться ночью."],
      nerve: ["Лекарство от судорог и нервной боли", "Успокаивает перевозбуждённые нервы. Применяется при судорогах и нервной боли."],
      muscle: ["Миорелаксант", "Расслабляет напряжённые мышцы и снимает судороги."],
      pain_inflammation: ["Противовоспалительное (НПВП)", "Уменьшает боль, отёк и температуру."],
      pain_fever: ["Обезболивающее и жаропонижающее", "Снимает боль и снижает температуру."],
      opioid: ["Сильное обезболивающее (опиоид)", "Снимает умеренную и сильную боль. Может вызывать привыкание."],
      steroid: ["Стероид", "Уменьшает воспаление и успокаивает иммунную систему. Применяется при аллергии, астме, артрите и болезнях кожи."],
      breathing: ["Лекарство для дыхания", "Расширяет дыхательные пути или уменьшает их отёк. Применяется при астме, ХОБЛ или аллергии."],
      allergy: ["Антигистаминное", "Снимает симптомы аллергии: чихание, насморк, зуд и крапивницу."],
      blood_thinner: ["Средство для разжижения крови", "Предотвращает опасные тромбы, которые могут вызвать инсульт или закупорить сосуды."],
      antiplatelet: ["Антиагрегант", "Не даёт клеткам крови слипаться, помогая предотвратить инфаркт и инсульт."],
      gout: ["Лекарство от подагры", "Предотвращает или лечит подагру — болезненный отёк суставов из-за мочевой кислоты."],
      prostate: ["Лекарство для простаты", "Облегчает проблемы с мочеиспусканием при увеличенной простате."],
      blood_flow: ["Лекарство для кровотока", "Улучшает кровоток. Применяется при эректильной дисфункции или лёгочной гипертензии."],
      hormone: ["Гормональное лекарство", "Применяется для контрацепции, при симптомах менопаузы или проблемах с менструацией."],
      mood: ["Стабилизатор настроения / антипсихотик", "Помогает выровнять настроение и мышление. Применяется при биполярном расстройстве, шизофрении и иногда при депрессии."],
      adhd: ["Лекарство от СДВГ (стимулятор)", "Улучшает концентрацию и внимание. Может вызывать привыкание."],
      memory: ["Лекарство для памяти", "Помогает памяти и мышлению при болезни Альцгеймера."],
      parkinson: ["Лекарство от болезни Паркинсона", "Лечит болезнь Паркинсона и синдром беспокойных ног."],
      migraine: ["Лекарство от мигрени", "Останавливает приступ мигрени после его начала."],
      supplement: ["Витамин или минерал", "Восполняет витамин или минерал, которого не хватает организму."],
      cough: ["Средство от кашля", "Успокаивает кашель."],
      gut_cramps: ["Средство от спазмов в животе", "Снимает спазмы желудка и кишечника, например при синдроме раздражённого кишечника."],
      glaucoma: ["Лекарство от глазного давления", "Снижает давление внутри глаза при глаукоме."],
      immune: ["Лекарство для иммунной системы", "Успокаивает слишком активную иммунную систему. Применяется при ревматоидном артрите, псориазе и некоторых видах рака."],
    },
  },

  tl: {
    label: "Para saan ito",
    note: "Maaaring inireseta ito ng doktor para sa ibang dahilan. Magtanong kung hindi sigurado.",
    classes: {
      antibiotic: ["Antibiotic", "Pinapatay ang bacteria para gamutin ang impeksyon. Hindi ito gumagana sa sipon o trangkaso."],
      antiviral: ["Antiviral", "Lumalaban sa mga virus, gaya ng nagdudulot ng singaw sa labi, shingles, o trangkaso."],
      antifungal: ["Antifungal", "Ginagamot ang impeksyon dahil sa fungus, gaya ng yeast infection."],
      blood_pressure: ["Gamot sa altapresyon", "Pinapababa ang presyon ng dugo para protektahan ang puso, utak, at bato."],
      heart_rate: ["Beta blocker", "Pinapabagal ang tibok ng puso at pinapababa ang presyon ng dugo. Ginagamit sa altapresyon at sakit sa puso."],
      water_pill: ["Diuretic (pampaihi)", "Tinutulungan ang katawan na ilabas ang sobrang tubig at asin, kaya bumababa ang manas at presyon ng dugo."],
      cholesterol: ["Gamot sa kolesterol", "Pinapababa ang kolesterol para mabawasan ang panganib ng atake sa puso at stroke."],
      diabetes: ["Gamot sa diabetes", "Pinapababa ang asukal sa dugo ng taong may diabetes."],
      thyroid: ["Thyroid hormone", "Pinapalitan ang thyroid hormone kapag mahina ang thyroid."],
      stomach_acid: ["Pampababa ng asido sa sikmura", "Binabawasan ang asido sa sikmura para gamutin ang heartburn, acid reflux, at ulcer."],
      nausea: ["Gamot sa pagduduwal", "Pinipigilan o pinapagaan ang pagduduwal, pagsusuka, o hilo sa biyahe."],
      antidepressant: ["Antidepressant", "Ginagamot ang depresyon at pagkabalisa sa pamamagitan ng pagbabalanse ng mga kemikal sa utak."],
      anxiety: ["Gamot sa pagkabalisa", "Binabawasan ang pagkabalisa."],
      sedative: ["Pampakalma (sedative)", "Pinapakalma ang pagkabalisa, panic, o pulikat ng kalamnan. Maaaring makasanayan."],
      sleep: ["Gamot pampatulog", "Tumutulong na makatulog at manatiling tulog."],
      nerve: ["Gamot sa kombulsyon at sakit ng ugat", "Pinapakalma ang sobrang aktibong ugat. Ginagamit sa kombulsyon at sakit ng ugat."],
      muscle: ["Muscle relaxant", "Pinaparelaks ang naninigas o pinupulikat na kalamnan."],
      pain_inflammation: ["Gamot sa sakit at pamamaga (NSAID)", "Binabawasan ang sakit, pamamaga, at lagnat."],
      pain_fever: ["Gamot sa sakit at lagnat", "Pinapawi ang sakit at pinapababa ang lagnat."],
      opioid: ["Malakas na gamot sa sakit (opioid)", "Pinapawi ang katamtaman hanggang matinding sakit. Maaaring makasanayan."],
      steroid: ["Steroid", "Binabawasan ang pamamaga at pinapakalma ang immune system. Ginagamit sa allergy, hika, arthritis, at problema sa balat."],
      breathing: ["Gamot sa paghinga", "Binubuksan ang daanan ng hangin o binabawasan ang pamamaga nito. Ginagamit sa hika, COPD, o allergy."],
      allergy: ["Antihistamine", "Pinapagaan ang sintomas ng allergy gaya ng pagbahing, sipon, pangangati, at pantal."],
      blood_thinner: ["Pampalabnaw ng dugo", "Pinipigilan ang mapanganib na pamumuo ng dugo na maaaring magdulot ng stroke o bumara sa ugat."],
      antiplatelet: ["Gamot laban sa pamumuo ng dugo", "Pinipigilan ang pagdidikit-dikit ng mga selula ng dugo para makaiwas sa atake sa puso at stroke."],
      gout: ["Gamot sa gout", "Pinipigilan o ginagamot ang gout, isang masakit na pamamaga ng kasukasuan dahil sa uric acid."],
      prostate: ["Gamot sa prostate", "Pinapagaan ang hirap sa pag-ihi dahil sa lumaking prostate."],
      blood_flow: ["Gamot sa daloy ng dugo", "Pinapabuti ang daloy ng dugo. Ginagamit sa erectile dysfunction o mataas na presyon ng dugo sa baga."],
      hormone: ["Gamot na hormone", "Ginagamit bilang kontrasepsyon, para sa sintomas ng menopause, o problema sa regla."],
      mood: ["Mood stabilizer / antipsychotic", "Tumutulong na patatagin ang mood at pag-iisip. Ginagamit sa bipolar disorder, schizophrenia, at minsan sa depresyon."],
      adhd: ["Gamot sa ADHD (stimulant)", "Pinapabuti ang pokus at atensyon. Maaaring makasanayan."],
      memory: ["Gamot sa memorya", "Tumutulong sa memorya at pag-iisip ng may Alzheimer's disease."],
      parkinson: ["Gamot sa Parkinson's", "Ginagamot ang Parkinson's disease at restless legs syndrome."],
      migraine: ["Gamot sa migraine", "Pinapahinto ang migraine kapag nagsimula na ito."],
      supplement: ["Bitamina o mineral", "Pinupunan ang bitamina o mineral na kulang sa katawan."],
      cough: ["Gamot sa ubo", "Pinapakalma ang ubo."],
      gut_cramps: ["Gamot sa pulikat ng tiyan", "Pinapagaan ang pulikat ng sikmura at bituka, gaya ng sa irritable bowel syndrome."],
      glaucoma: ["Gamot sa presyon ng mata", "Pinapababa ang presyon sa loob ng mata para gamutin ang glaucoma."],
      immune: ["Gamot sa immune system", "Pinapakalma ang sobrang aktibong immune system. Ginagamit sa rheumatoid arthritis, psoriasis, at ilang uri ng kanser."],
    },
  },
};
